spring.application.name=UsersTable

#DB
spring.datasource.url=jdbc:postgresql://localhost:5433/users
spring.datasource.username=postgres
spring.datasource.password=postgres

#Hibernate
spring.jpa.hibernate.ddl-auto=update
